---
title: "Untitled"
author: "deepika"
date: "2025-02-18"
output: html_document
---

# Load necessary libraries

```{r}
library(tidyverse)
library(caret)
library(dplyr)
```

# Load the data
```{r}
dataset=read.csv("C:/Users/deepi/Desktop/deeps/airplane_price_dataset.csv")
```

```{r}
dim(dataset)
```

```{r}
sum(is.na(data))
```

```{r}
head(dataset)
```

```{r}
str(dataset)
```

```{r}
head(dataset)
```

```{r}
colSums(is.na(dataset))
```

```{r}
str(dataset)
```

```{r}
summary(dataset)
```

```{r}
colnames(dataset)
```

# Rename columns for easier handling
```{r}
data <- dataset %>%rename(Model = Model,
Year =Üretim.Yılı ,
Num_Engines = Motor.Sayısı,
Engine_Type = Motor.Türü ,
Capacity = Kapasite,
Range_km = Menzil..km.,
Fuel_Consumption_Lph = Yakıt.Tüketimi..L.saat. ,
Maintenance_Cost_per_Hour = Saatlik.Bakım.Maliyeti....,
Age = Yaş,
Sales_Region = Satış.Bölgesi,
Price = Fiyat....)                
```

```{r}
print("Column names in the Dataset")
colnames(dataset)
print("Column names after Alteration")
colnames(data)
```

```{r}
data <- data[, !(colnames(data) %in% "Age")]
```

```{r}
data
```

```{r}
colnames(data)
```

```{r}
# Convert categorical variables to factors
data$Model <- as.factor(data$Model)
data$Engine_Type <- as.factor(data$Engine_Type)
data$Sales_Region <- as.factor(data$Sales_Region)
```

```{r}
# Split data into training and testing sets
set.seed(123)
trainIndex <- createDataPartition(data$Price, p = 0.8, list = FALSE)
trainData <- data[trainIndex, ]
testData <- data[-trainIndex, ]
```

```{r}
# Train a linear regression model
model <- lm(Price ~ Year + Num_Engines + Engine_Type + Capacity + Range_km + Fuel_Consumption_Lph + Maintenance_Cost_per_Hour + Sales_Region,data = trainData)
```

```{r}
# Model summary
summary(model)
```
```{r}
# Predict on test data
testData$Predicted_Price <- predict(model, newdata = testData)
```

```{r}
# Evaluate model performance
mse <- mean((testData$Price - testData$Predicted_Price)^2)
r2 <- cor(testData$Price, testData$Predicted_Price)^2
rmse <- sqrt(mse)
mae <- mean(abs(testData$Price - testData$Predicted_Price))
accuracy <- (1 - (mae / mean(testData$Price))) * 100

```

```{r}
# Print evaluation metrics
cat("Mean Squared Error:", mse, "\n")
cat("Root Mean Squared Error:", rmse, "\n")
cat("Mean Absolute Error:", mae, "\n")
cat("R-squared:", r2, "\n")
cat("Accuracy Percentage:", accuracy, "%\n")
```

# Frequency count of aircraft manufacturers
```{r}
table(data$Model) 
```


```{r}
plot(model)
```


























